#!/bin/sh
if [ -z "$(xrandr --listactivemonitors | grep 'DP-0~1')"]; then
	xrandr --setmonitor DP-0~1 1920/435x1600/370+1920+0 DP-0
	xrandr --setmonitor DP-0~2 1920/435x1080/245+3840+0 none
	xrandr --setmonitor DP-0~3 1920/435x520/117+3840+1080 none
	#xrandr --fb 1920x1080
else
	xrandr --delmonitor DP-0~1
	xrandr --delmonitor DP-0~2
	xrandr --delmonitor DP-0~3
fi

source ~/dotfiles/polybar/launch.sh
